paths:
  uploads: uploads
  uploads_use_relative_path: false
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide
  column-sizes:
    col-6: One Half
    col-12: Full Width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half (Stacked)
    col-4_sm-12: One Third (Stacked)
    col-3_sm-12: One Quarter (Stacked)
  background-modes:
    - Light Mode
    - Featured Mode
    - Dark Mode
data_config: {}
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
